### ISSUE TITLE
Hosting TADS 3.1 Online Play Story Files

### ISSUE THREAD

**Issue by mikes67** [iftechfoundation/ifcomp#209]
As I understand it, TADS 3.1 story files enabled for Online Play (.t3 files) cannot be hosted by/on the IFComp.  I was able to work-around this issue a couple of years ago but am wondering if this can be added to the enhancement list.  Thanks!

**Comment by midiguru** [comment]
I second this request. I'm working on a TADS 3 game for the IFComp. I can easily host the Web-capable version of the story on my own server, so that others can play it, but I don't know how this setup comports with the Comp rules. Having it hosted on a server associated with the Comp would obviously be preferable, if only because you would have oversight.

**Comment by jmacdotorg** [comment]
Thanks for this suggestion! We've started to discuss this internally; will do some further research and update this ticket as warranted.

**Comment by curiousdannii** [comment]
The IFComp website supports online play of normal TADS 3 games, but not TADS 3 Web UI games. However Web UI is basically abandoned now. I don't think the IFComp site should be supporting them when basically nothing else does at present.
