### ISSUE TITLE
two "submit game information" buttons in http://dev.ifcomp.org/entry/create

### ISSUE THREAD

**Issue by andrewschultz** [iftechfoundation/ifcomp#219]
This may be trivial aesthetics, but having the two buttons labeled "submit game information" could leave a new user slightly confused.

I assume the first one only updates the basic information above it, and the second updates everything up to the top of the page, and not just the information between the two buttons. I'm 98% sure about this, but maybe we should make it 100%?

So I think if we could rename them "submit basic game information" and "submit full game information" that would be helpful.

There is also the possibility that a user wants to change both basic and full information., and they may be unsure the "submit game information" button submits the basic information. Is it worthwhile to make a brief note to reassure the user that "full game information" will also update any basic information changes?

**Comment by jmacdotorg** [comment]
Nope, they both do the exact same thing, submitting the entire form.

The upper button appears *only* for new entries/intents, and not when updating an existing entry (or intent). It has this text above it:

> If you're only declaring your intent to enter at this time, then you may use the button below to submit this form right now with just its title, subtitle, and platform information. That will serve as your intent, and you'll be able to update, rename, or otherwise modify your entry as much as you please through the September 1 deadline.

This is how it's worked since 2014. (Granted that I *just now* clarified the text to add a reference to platform information, given recent work, so it was very much worth the revisit!)

Given this information, does this seem sufficiently clear to you?

**Comment by andrewschultz** [comment]
Yes it does.

However, would you mind leaving this open so that I can verify, indeed, that the button disappears when I edit an entry? It's a useful enough test case, I would spend time checking off on it with a new build once #217 is fixed.

**Comment by andrewschultz** [comment]
After tinkering with things, I'm confident that this will work well for entrants who want to create and modify their works. So, closing.
