### ISSUE TITLE
Authors need to be reachable by the organizers

### ISSUE THREAD

**Issue by mjmusante** [iftechfoundation/ifcomp#231]
Some authors use throwaway email addresses to register and upload games, despite the ability for them to set email_is_public to false. This makes it difficult for the comp organizers to get in touch with authors should the need arise. Without specifying implementation details: the software should give a way for authors to submit an email address that will be live at least through the end of prize distribution, and/or a way to say that the "regular" email meets that criteria

**Comment by jmacdotorg** [comment]
Hmm, I don't know that this is something we can practically fix with software.

We did specify the importance of real email addresses in the new handbook that Jacq and I published earlier this month. Since we've already established "please don't use a burner address" in that handbook, I don't think we should follow up by inventing ways to make the use of burner addresses more convenient. So, I'm calling this done-enough.
