### ISSUE TITLE
Refactor IFComp/lib/IFComp/Schema/Result/Entry.pm 

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#243]
IFComp/lib/IFComp/Schema/Result/Entry.pm

This file constructs the online play pages, but is written such that the only options are Zcode or Glulx. Please refactor this to be more generic so that other platforms can be added more easily.

**Comment by jmacdotorg** [comment]
This isn't really an issue with how the software operates, so I will acknowledge the critique and close it as an issue.

I'll also comment that the "Web" platform is the generic way that authors can say "This game is meant to be played online", for any development platform at all.

Z-Code/Glulx get special treatment in the codebase because of the tortures and mutations that the web app puts their source through for the sake of transcript support.

**Comment by curiousdannii** [comment]
Will it just be enough to add in extra options here? 

https://github.com/iftechfoundation/ifcomp/blob/master/IFComp/lib/IFComp/Schema/Result/Entry.pm#L994
