### ISSUE TITLE
Switch from MD5 to bcrypt (or similar)

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifcomp#29]
MD5 is now very insecure. Please consider switching to bcrypt, scrypt ot something similar. There are perl implementations at least for bcrypt: https://metacpan.org/pod/Crypt::Eksblowfish::Bcrypt

**Comment by jmacdotorg** [comment]
Just to keep this issue warm, this article presents an interesting solution: http://www.fngtps.com/2010/moving-to-a-safer-password-solution/

**Comment by jmacdotorg** [comment]
This issue has stayed open for three years because (1) migrating between two password encryption systems is a pain, and (2) the fact that three websites using it makes it extra-painful.

While I agree that MD5 isn't the best system, I'm tempted to close this issue on grounds that what we have is good enough, especially when paired with basic monitoring against attack and pretty good server security practices on our end.

If I understand correctly, the danger is not in the password being decrypted (which is essentially impossible), but that access to the account can be jimmied open with a brute-force dictionary attack, given that the "collision space" for MD5 passwords is larger than is optimal?

If so, then the worst-case scenario is a malefactor taking control of someone else's IFComp/Introcomp/XYZZYAwards login, right? That wouldn't be great, but to my eye there's very little super-interesting that one can do with a suborned account, at least at present and for the foreseeable future. It seems very unlikely to me that it would be worth anyone's effort to try -- and even then, their attempt would be extremely obvious, since there's nothing to do but spam the IFComp server with password attempts.

**Comment by erkyrath** [comment]
The worst-case scenario is if someone gets access to machine and steals the password database. Then they find that the problem of cracking everybody's IFComp login is much easier than it should be. I.e. we're a step closer to "storing passwords in cleartext" than we really ought to be.

**Comment by jmacdotorg** [comment]
I agree with your concluding statement, but I would posit that we're still on the right side of safety, enough to just punt this issue.

(And frankly we've already blown the "uh oh, hope nobody finds out that IFComp logins are MD5" thing as soon as this thread was first posted in 2014...)

**Comment by curiousdannii** [comment]
The danger is because most people reuse passwords on multiple sites. Though there's nothing valuable here, we don't want to be the weak link which exposes people's more valuable data on other sites. 

Are the passwords at least uniquely salted?

**Comment by jmacdotorg** [comment]
Passwords set prior to 2014 used a hardcoded salt value; passwords set since 2014 have used unique-per-user salt.

To make sure we're talking about the same thing, confirm that the danger you're thinking of is this: Alice finds, via a dictionary attack on ifcomp.org's login page (or -- worst-case -- a dump she has obtained of IFComp's database) that "foo" works as a password for bob@example.com's IFComp account. This doesn't mean that Bob chose "foo" as a password, only that it MD5-collides with whatever password he did choose. Alice now knows that "foo" *might* work as a password on any other web service Bob uses, so long as (1) that service also encrypts its passwords with MS5, and (2) Bob re-used the same password there.

Is that a correct summary?

**Comment by curiousdannii** [comment]
How many of those pre-2014 passwords are still around? Perhaps just those could be invalidated.

Yeah that's a good summary. I'm not an expert at security, but I have been forced to change my passwords from password leaks on other sites. (I should start using a password manager I guess.)

Another thing entirely really: adding support for OAuth 2 would be nice, so that we could log in through other 2FA secured systems.

**Comment by adherzog** [comment]
I'm very much against closing this issue as something that doesn't need to be addressed.

I'd like to steer the conversation away from 'is MD5 good enough' (which it absolutely isn't, IMO) to 'what are the technical difficulties with making the change'.

> (1) migrating between two password encryption systems is a pain, and

I've made this sort of transition at least twice before, on applications using the same software stack in use with the IFComp app. I'd be happy to do it again on this project.

It's worth noting that we can update each account's hashing method on a successful login - we don't need to wait for (or force) users to change their password. And we can update salts at the same time, too.

> (2) the fact that three websites using it makes it extra-painful.

Can somebody tell me more about this? Assuming the main IFComp site is one of the three, what are the other two sites? How do they interact with the user records? Do we pass the MD5 hash off to other websites and let them verify passwords against it?

**Comment by erkyrath** [comment]
The other two sites are http://xyzzyawards.org/awards/login.php and http://www.allthingsjacq.com/introcomp/ . I don't know anything about how they interact, however.

**Comment by danshiovitz** [comment]
They can be ignored for purposes of this - when people log into one of them, their password gets sent to the main ifcomp site which auths them. I don't remember if the code to auth them uses the main flow or not, but in any case we can change the implementation without affecting the other sites.

**Comment by adherzog** [comment]
Okay - I'm confident this is something we can do. I've assigned this issue to myself - I expect I'll submit a PR in the next week or two.
